# Generated by Django 4.2.19 on 2025-02-28 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('slot_duration', models.IntegerField(default=15, help_text='Duration of each appointment slot in minutes')),
                ('max_appointments_per_slot', models.IntegerField(default=1, help_text='Maximum number of appointments allowed per time slot')),
            ],
        ),
    ]
